#!/usr/bin/env python3
"""
Generate build information header file
Increments build number and adds timestamp
"""

import os
import datetime
import subprocess

# Import PlatformIO environment (if running as extra_script)
try:
    Import("env")
    project_root = env.get("PROJECT_DIR")
except:
    # Fallback for standalone execution
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

# Paths
build_num_file = os.path.join(project_root, "build_number.txt")
output_file = os.path.join(project_root, "include", "build_version.h")

# Read and increment build number
build_number = 1
if os.path.exists(build_num_file):
    try:
        with open(build_num_file, 'r') as f:
            build_number = int(f.read().strip()) + 1
    except:
        build_number = 1

# Write new build number
with open(build_num_file, 'w') as f:
    f.write(str(build_number))

# Get git info (if available)
git_hash = "unknown"
git_branch = "unknown"
try:
    git_hash = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'],
                                       cwd=project_root,
                                       stderr=subprocess.DEVNULL).decode('ascii').strip()
    git_branch = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
                                         cwd=project_root,
                                         stderr=subprocess.DEVNULL).decode('ascii').strip()
except:
    pass

# Generate timestamp
timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
date_only = datetime.datetime.now().strftime("%Y%m%d")

# Generate header file
header_content = f"""/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER {build_number}
#define BUILD_TIMESTAMP "{timestamp}"
#define BUILD_DATE "{date_only}"
#define GIT_HASH "{git_hash}"
#define GIT_BRANCH "{git_branch}"

#endif // BUILD_VERSION_H
"""

# Write header file
with open(output_file, 'w') as f:
    f.write(header_content)

print(f"Build info generated: Build #{build_number}, {timestamp}")
print(f"Git: {git_branch}@{git_hash}")
