/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 630
#define BUILD_TIMESTAMP "2025-12-17 22:32:49"
#define BUILD_DATE "20251217"
#define GIT_HASH "05418ff"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
