/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 951
#define BUILD_TIMESTAMP "2026-01-03 17:26:00"
#define BUILD_DATE "20260103"
#define GIT_HASH "2698a15"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
