/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 1384
#define BUILD_TIMESTAMP "2026-03-16 22:29:09"
#define BUILD_DATE "20260316"
#define GIT_HASH "d0a5c67"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
